function [name,all] = tosca_name_dict( index )
    all = {         ...
        'cat',      ...
        'centaur',  ...
        'dog',      ...
        'gorilla',  ...
        'horse',    ...
        'lioness',  ...
        'wolf',     ...
        'seahorse', ...
        'victoria', ...
        'michael',  ...
        'david'};
    
    if index < numel(all)
        name = all{index};
    else
        error('Index out of bounds.');
    end
end